---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: longhorn-frontend

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: longhorn-manager

      securityContext:
        runAsUser: 0

      containers:
        - name: server
          image: longhorn-frontend
          imagePullPolicy: IfNotPresent

          env:
            - name: LONGHORN_MANAGER_IP
              value: "http://longhorn-manager:9500"

          ports:
            - name: http
              containerPort: 8000

...
