---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: longhorn-manager

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-manager

subjects:
  - kind: ServiceAccount
    name: longhorn-manager

...
