---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml

  - service.yml
  - daemonset.yml

commonLabels:
  app: longhorn-manager
  app.kubernetes.io/component: manager

configMapGenerator:
  - name: longhorn-settings
    files:
      - settings.yaml=settings.yml
  - name: longhorn-storageclass
    files:
      - storageclass.yaml=storageclass.yml
    options:
      disableNameSuffixHash: true

...
