---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: longhorn-driver

spec:
  replicas: 1

  template:
    metadata:
      annotations:
        longhorn-manager-image: longhorn-manager

    spec:
      serviceAccountName: longhorn-manager

      securityContext:
        runAsUser: 0

      initContainers:
        - name: wait
          image: wait-for
          imagePullPolicy: IfNotPresent
          command:
            - wait-for
            - -it
            - longhorn-manager:9500

      containers:
        - name: server
          image: longhorn-manager
          imagePullPolicy: IfNotPresent

          command:
            - longhorn-manager
            - deploy-driver
            - --manager-image
            - $(MANAGER_IMAGE)
            - --manager-url
            - http://longhorn-manager:9500/v1

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

            - name: MANAGER_IMAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['longhorn-manager-image']

          ports:
            - name: http
              containerPort: 8000

...
